language: php

php:
  - "7.2"
  - "7.3"

install:
  - composer install

script:
  - composer check
#  - ./vendor/bin/phpcs
#  - ./vendor/bin/phpstan analyse
#  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
#  - ./vendor/bin/infection -s --min-msi=100 --min-covered-msi=100
